/**
 * Mars Simulation Project
 * NuclearReactor.java
 * @version 2.75 2003-03-04
 * @author Scott Davis
 */
 
package org.mars_sim.msp.simulation.structure.building;

import org.mars_sim.msp.simulation.structure.building.function.PowerGeneration;

/**
 * The NuclearReactor class represents a 
 * fission nuclear reactor.
 */
public class NuclearReactor extends Building implements PowerGeneration {
    
    // Base power (kWe) generated by the reactor.
    private static final double BASE_POWER_GENERATION = 100D;
    
    /**
     * Constructor
     * @param manager - building manager.
     */
    public NuclearReactor(BuildingManager manager) {
        // Use Bulding constructor
        super("Nuclear Reactor", manager);
        
        // Add scope string to malfunction manager.
        malfunctionManager.addScopeString("Power Generation");
        malfunctionManager.addScopeString("Nuclear Reactor");
    }
    
    /**
     * Gets the amount of electrical power generated.
     * @return power generated in kW
     */
    public double getGeneratedPower() {
        return BASE_POWER_GENERATION;
    }
    
    /**
     * Gets the power this building currently uses.
     * @return power in kW.
     */
    public double getPowerUsed() {
        return 0D;
    }
    
    /**
     * Gets the power this building currently requires for full-power mode.
     * @return power in kW.
     */
    public double getFullPowerRequired() {
        // Produces more power than it uses.
        return 0D;
    }
    
    /**
     * Gets the power the building requires for power-down mode.
     * @return power in kW.
     */
    public double getPoweredDownPowerRequired() {
        // Produces more power than it uses.
        return 0D;
    }
}
