/**
 * Mars Simulation Project
 * GreenhouseFacility.java
 * @version 2.72 2001-04-25
 * @author Scott Davis
 */

package org.mars_sim.msp.simulation;

/**
 * The GreenhouseFacility class represents the greenhouses in a settlement.
 * It defines the amount of fresh and dried foods generated by the greenhouses.
 */

public class GreenhouseFacility extends Facility {

    // Data members
    private double fullHarvestAmount; // Number of food units the greenhouse can produce at full harvest.
    private double workLoad; // Number of work-hours tending greenhouse required during growth period for full harvest.
    private double growingWork; // Number of work-hours completed for growing phase.
    private double workCompleted; // Number of work-hours completed for current phase.
    private double growthPeriod; // Number of days for growth period.
    private double growthPeriodCompleted; // Number of days completed in current growth period..
    private String phase; // "Inactive", "Planting", "Growing" or "Harvesting"

    /** Constructor for random creation. 
     *  @param manager of the greenhouse facility
     */
    public GreenhouseFacility(FacilityManager manager, LivingQuartersFacility quarters) {

        // Use Facility's constructor.
        super(manager, "Greenhouse");

        // Initialize data members
        workCompleted = 0D;
        growthPeriod = 10D;
        growthPeriodCompleted = 0D;
        phase = "Inactive";

        // Determine full harvest amount.
	fullHarvestAmount = growthPeriod * quarters.getMaximumCapacity();

        // Determine work load based on full harvest amount.
        // (80hrs for 200 food - 120hrs for 300 food)
        workLoad = .4D * fullHarvestAmount;
    }

    /** Constructor for set values (used later when facilities can be built or upgraded.) 
     *  @param manager manager of the greenhouse facility
     *  @param workLoad tending work required for a full harvest (in work-hours)
     *  @param growthPeriod time required to grow crops (in days)
     *  @param fullHarvestAmount number of food units the greenhouse can produce at full harvest
     */
    public GreenhouseFacility(FacilityManager manager, float workLoad, float growthPeriod, float fullHarvestAmount) {

        // Use Facility's constructor.

        super(manager, "Greenhouse");

        // Initialize data members.

        this.workLoad = workLoad;
        this.growthPeriod = growthPeriod;
        this.fullHarvestAmount = fullHarvestAmount;
        workCompleted = 0D;
        growthPeriodCompleted = 0D;
        phase = "Inactive";
    }

    /** Returns the harvest amount of the greenhouse. 
     *  @return number of food units the greenhouse can produce at full harvest
     */
    public double getFullHarvestAmount() {
        return fullHarvestAmount;
    }

    /** Returns the work load of the greenhouse. (in work-hours) 
     *  @return tending work required for a full harvest (in work hours)
     */
    public double getWorkLoad() {
        return workLoad;
    }

    /** Returns the work completed in this cycle in the growing phase. 
     *  @return work completed so far in the growing phase (in work hours)
     */
    public double getGrowingWork() {
        return growingWork;
    }

    /** Returns the growth period of the greenhouse. (in days) 
     *  @return time required to grow crops (in days)
     */
    public double getGrowthPeriod() {
        return growthPeriod;
    }

    /** Returns the current work completed on the current phase. (in work-hours) 
     *  @return work completed so far in this phase (in work hours)
     */
    public double getWorkCompleted() {
        return workCompleted;
    }

    /** Returns the time completed of the current growth cycle. (in days) 
     *  @return time completed in growth cycle (in days)
     */
    public double getTimeCompleted() {
        return growthPeriodCompleted;
    }

    /** Returns true if a harvest cycle has been started. 
     *  @return current phase
     */
    public String getPhase() {
        return phase;
    }

    /** Adds work to the work completed on a growth cycle. 
     *  @param work-seconds added to growth cycle
     */
    public void addWorkToGrowthCycle(double seconds) {

        double plantingWork = 4D * 60D * 60D;
        double harvestingWork = (.25D * fullHarvestAmount) * 60D * 60D;
        double workInPhase = (workCompleted * 60D * 60D) + seconds;

        if (phase.equals("Inactive"))
            phase = "Planting";

        if (phase.equals("Planting")) {
            if (workInPhase >= plantingWork) {
                workInPhase -= plantingWork;
                phase = "Growing";
            }
        }

        if (phase.equals("Growing"))
            growingWork = workInPhase / (60D * 60D);

        if (phase.equals("Harvesting")) {
            if (workInPhase >= harvestingWork) {
                workInPhase -= harvestingWork;
                double foodProduced = fullHarvestAmount * (growingWork / workLoad);
                ((StoreroomFacility) manager.getFacility("Storerooms")).addFood(foodProduced);
                phase = "Planting";
                growingWork = 0D;
                growthPeriodCompleted = 0D;
            }
        }

        workCompleted = workInPhase / (60D * 60D);
    }

    /** Override Facility's timePasses method to allow for harvest cycle. 
     *  @param number of seconds of time passing
     */
    void timePasses(double seconds) {

        if (phase.equals("Growing")) {
            growthPeriodCompleted += (seconds / (60D * 60D * 25D));
            if (growthPeriodCompleted >= growthPeriod) {
                phase = "Harvesting";
                workCompleted = 0F;
            }
        }
    }
}
