/**
 * Mars Simulation Project
 * GreenhouseFacility.java
 * @version 2.71 2001-01-29
 * @author Scott Davis
 */

package org.mars_sim.msp.simulation;

/**
 * The GreenhouseFacility class represents the greenhouses in a settlement.
 * It defines the amount of fresh and dried foods generated by the greenhouses.
 */

public class GreenhouseFacility extends Facility {

    // Data members
    private float fullHarvestAmount; // Number of food units the greenhouse can produce at full harvest.
    private float workLoad; // Number of work-hours tending greenhouse required during growth period for full harvest.
    private float growingWork; // Number of work-hours completed for growing phase.
    private float workCompleted; // Number of work-hours completed for current phase.
    private float growthPeriod; // Number of days for growth period.
    private float growthPeriodCompleted; // Number of days completed in current growth period..
    private String phase; // "Inactive", "Planting", "Growing" or "Harvesting"

    /** Constructor for random creation. 
     *  @param manager of the greenhouse facility
     */
    public GreenhouseFacility(FacilityManager manager, LivingQuartersFacility quarters) {

        // Use Facility's constructor.
        super(manager, "Greenhouse");

        // Initialize data members
        workCompleted = 0F;
        growthPeriod = 10F;
        growthPeriodCompleted = 0F;
        phase = "Inactive";

        // Determine full harvest amount.
	fullHarvestAmount = growthPeriod * quarters.getMaximumCapacity();

        // Determine work load based on full harvest amount.
        // (80hrs for 200 food - 120hrs for 300 food)
        workLoad = .4F * fullHarvestAmount;
    }

    /** Constructor for set values (used later when facilities can be built or upgraded.) 
     *  @param manager manager of the greenhouse facility
     *  @param workLoad tending work required for a full harvest (in work-hours)
     *  @param growthPeriod time required to grow crops (in days)
     *  @param fullHarvestAmount number of food units the greenhouse can produce at full harvest
     */
    public GreenhouseFacility(FacilityManager manager, float workLoad, float growthPeriod, float fullHarvestAmount) {

        // Use Facility's constructor.

        super(manager, "Greenhouse");

        // Initialize data members.

        this.workLoad = workLoad;
        this.growthPeriod = growthPeriod;
        this.fullHarvestAmount = fullHarvestAmount;
        workCompleted = 0F;
        growthPeriodCompleted = 0F;
        phase = "Inactive";
    }

    /** Returns the harvest amount of the greenhouse. 
     *  @return number of food units the greenhouse can produce at full harvest
     */
    public float getFullHarvestAmount() {
        return fullHarvestAmount;
    }

    /** Returns the work load of the greenhouse. (in work-hours) 
     *  @return tending work required for a full harvest (in work hours)
     */
    public float getWorkLoad() {
        return workLoad;
    }

    /** Returns the work completed in this cycle in the growing phase. 
     *  @return work completed so far in the growing phase (in work hours)
     */
    public float getGrowingWork() {
        return growingWork;
    }

    /** Returns the growth period of the greenhouse. (in days) 
     *  @return time required to grow crops (in days)
     */
    public float getGrowthPeriod() {
        return growthPeriod;
    }

    /** Returns the current work completed on the current phase. (in work-hours) 
     *  @return work completed so far in this phase (in work hours)
     */
    public float getWorkCompleted() {
        return workCompleted;
    }

    /** Returns the time completed of the current growth cycle. (in days) 
     *  @return time completed in growth cycle (in days)
     */
    public float getTimeCompleted() {
        return growthPeriodCompleted;
    }

    /** Returns true if a harvest cycle has been started. 
     *  @return current phase
     */
    public String getPhase() {
        return phase;
    }

    /** Adds work to the work completed on a growth cycle. 
     *  @param work-seconds added to growth cycle
     */
    public void addWorkToGrowthCycle(int seconds) {

        float plantingWork = 4F * 60F * 60F;
        float harvestingWork = (.25F * fullHarvestAmount) * 60F * 60F;
        float workInPhase = (workCompleted * 60F * 60F) + seconds;

        if (phase.equals("Inactive"))
            phase = "Planting";

        if (phase.equals("Planting")) {
            if (workInPhase >= plantingWork) {
                workInPhase -= plantingWork;
                phase = "Growing";
            }
        }

        if (phase.equals("Growing"))
            growingWork = workInPhase / (60F * 60F);

        if (phase.equals("Harvesting")) {
            if (workInPhase >= harvestingWork) {
                workInPhase -= harvestingWork;
                double foodProduced = fullHarvestAmount * (growingWork / workLoad);
                ((StoreroomFacility) manager.getFacility("Storerooms")).addFood(foodProduced);
                phase = "Planting";
                growingWork = 0F;
                growthPeriodCompleted = 0F;
            }
        }

        workCompleted = workInPhase / (60F * 60F);
    }

    /** Override Facility's timePasses method to allow for harvest cycle. 
     *  @param number of seconds of time passing
     */
    void timePasses(int seconds) {

        if (phase.equals("Growing")) {
            growthPeriodCompleted += (seconds / (60F * 60F * 25F));
            if (growthPeriodCompleted >= growthPeriod) {
                phase = "Harvesting";
                workCompleted = 0F;
            }
        }
    }
}
