#!/usr/bin/env bash
echo "Launching Mars Simulation Project..."
if command -v java >/dev/null 2>&1;
then
    echo >&2 "Java found"
else
    echo >&2 "You don't have Java. Aborting"
    exit 1
fi

if [[ $(java -version 2>&1) == *"OpenJDK"* ]]; 
then 
    echo 'You are using OpenJDK'
else 
    echo 'You are not using OpenJDK'
fi

java -Djava.util.logging.config.file=logging.properties -cp .::jars/ org.mars_sim.main.MarsProject -Xms256m -Xmx1536m -new