package org.mars_sim.msp.restws.mapper;


import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import org.mars_sim.msp.core.person.Person;
import org.mars_sim.msp.restws.model.PersonDetails;

/**
 * This interface represents a Mapper use to converts from an Entity to the lightweight DTO representation.
 * An implementation is generated by the MapStruct code generator.
 */
@Mapper(componentModel="spring",
		uses={UnitReferenceMapper.class,MissionReferenceMapper.class})
public interface PersonDetailsMapper {
	// This should contain the same mappings as the PersonSummary Mapper
	// TODO: What about Skills ?
	@Mappings({
		@Mapping(source="identifier", target="id"),
		@Mapping(source="baseMass", target="mass"),
		@Mapping(source="vehicle", target="vehicle"),
		@Mapping(source="settlement", target="settlement"),
		@Mapping(source="physicalCondition.fatigue", target="fatigue"),
		@Mapping(source="physicalCondition.hunger", target="hunger"),
		@Mapping(source="physicalCondition.stress", target="stress"),
		@Mapping(source="physicalCondition.performanceFactor", target="performance"),
		@Mapping(source="physicalCondition.healthSituation", target="healthSituation"),
		@Mapping(source="mind.mission", target="mission"),
		@Mapping(source="mind.MBTI.typeString", target="personalityType"),
		@Mapping(source="mind.taskManager.phase.name", target="taskPhase"),
		@Mapping(source="mind.taskManager.taskName", target="task")
	})
	PersonDetails personToPersonDetail(Person person);
}
