name: Build Installers

# This workflow builds native installers for multiple platforms
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build-installers:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact-pattern: '*.deb *.rpm'
            app-images: true
          - os: windows-latest  
            platform: windows
            artifact-pattern: '*.msi *.exe'
            app-images: true
          - os: macos-latest
            platform: macos
            artifact-pattern: '*.dmg *.pkg'
            app-images: true
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.platform }} installers
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Extract version
      id: version
      shell: bash
      run: |
        VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Build base packages
      run: mvn --file pom.xml -B package -Dmaven.test.skip=true
      
    - name: Build app-images  
      if: matrix.app-images
      run: mvn -B package -Pjpackage -Dmaven.test.skip=true
      
    - name: List built files
      shell: bash
      run: |
        echo "=== App Images ==="
        find . -name "app-images" -type d -exec ls -la {} \; || true
        echo "=== Installers ==="  
        find . -name "installers" -type d -exec ls -la {} \; || true
        echo "=== ZIP Distribution ==="
        find . -name "*.zip" -path "*/target/*" -ls || true
        
    - name: Upload ZIP distribution
      uses: actions/upload-artifact@v3
      with:
        name: mars-sim-${{ steps.version.outputs.version }}-${{ matrix.platform }}-zip
        path: mars-sim-dist/target/mars-sim-*.zip
        
    - name: Upload app-images
      if: matrix.app-images
      uses: actions/upload-artifact@v3
      with:
        name: mars-sim-${{ steps.version.outputs.version }}-${{ matrix.platform }}-app-images
        path: |
          mars-sim-installer/target/app-images/
        if-no-files-found: ignore
        
    - name: Upload installers 
      uses: actions/upload-artifact@v3
      with:
        name: mars-sim-${{ steps.version.outputs.version }}-${{ matrix.platform }}-installers
        path: |
          mars-sim-installer/target/installers/
        if-no-files-found: ignore